# Generated by Django 2.1.2 on 2020-03-28 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorToDecisionBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('threshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('execution', models.CharField(max_length=50)),
                ('execution_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('magnitude', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='decisionbox',
            name='questions',
            field=models.ManyToManyField(to='test_kit.Question'),
        ),
        migrations.AddField(
            model_name='decisionbox',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connectortodecisionbox',
            name='decision_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_kit.DecisionBox'),
        ),
        migrations.AddField(
            model_name='connector',
            name='connect_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_kit.DecisionBox'),
        ),
        migrations.AddField(
            model_name='connector',
            name='connect_to',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_kit.ConnectorToDecisionBox'),
        ),
        migrations.AddField(
            model_name='connector',
            name='operation',
            field=models.ManyToManyField(to='test_kit.Operation'),
        ),
        migrations.AddField(
            model_name='connector',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='initial_decision_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_kit.DecisionBox'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
