# Generated by Django 2.1.2 on 2020-03-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_kit', '0002_auto_20200329_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisionbox',
            old_name='algorthm',
            new_name='algorithm',
        ),
        migrations.AlterField(
            model_name='connector',
            name='connect_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_kit.ConnectorToDecisionBox'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='execution',
            field=models.CharField(choices=[('SaySomething', 'saysomething'), ('PrintSomething', 'printsomething')], max_length=50),
        ),
    ]
